name: MTS QA Homework4

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu_latest

    steps:
      - name: "Использование main-репозитория"
        uses: actions/checkout/@3
      - name: "Запуск тестов"
        run: gradle clean test
        continue-on-error: true
      - name: "Генерация allure report"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with: 
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: target/allure-history

      - name: "Создание ветки gh-pages, содержащей allure-report"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-history